name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: Confirm build is ready for release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
